# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: r-spatial
email: edzer.pebesma@uni-muenster.de 
description: > # this means to ignore newlines until "baseurl:"
   R Spatial software blogs and ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://r-spatial.org/" # the base hostname & protocol for your site
twitter_username: edzerpebesma
github_username:  r-spatial

# Build settings
markdown: kramdown

# Plugin for redirects
plugins:
  - jekyll-redirect-from
